/* eslint-disable prettier/prettier */
export const TASK_DEPLOY_FEECHAIN_NFT = "DEPLOY_FEECHAIN";
export const TASK_DEPLOY_MINTINGCHAIN_NFT = "DEPLOY_MINTINGCHAIN";
export const TASK_SET_LINKER = "SET_LINKER";
export const TASK_SET_FEES_TOKEN = "SET_FEES_TOKEN";
export const TASK_STORE_DEPLOYMENTS = "STORE_DEPLOYMENTS";
export const TASK_MAP_CONTRACT = "MAP_CONTRACTS";
export const TASK_UNMAP_CONTRACT = "UNMAP_CONTRACTS";
export const TASK_APPROVE_FEES = "APPROVE_FEES";
export const TASK_SET_CROSSCHAIN_GAS = "SET_CROSSCHAIN_GAS";
export const TASK_SET_NFT_FEES_TOKEN = "SET_NFT_FEES_TOKEN";
export const TASK_SET_NFT_FEES = "SET_NFT_FEES";
